numero1 = eval(input("ingrese numero 1"))
numero2 = eval(input("ingrese numero 2"))
numero3 = eval(input("ingrese numero 3"))
if(numero1 <=numero2 and numero2 <=numero3):
  print("{} ,{} ,{}".format(numero1, numero2, numero3))
if(numero2 <=numero1 and numero1 <=numero3):
  print("{} ,{} ,{}".format(numero2, numero1, numero3))
if(numero2 <=numero3 and numero3 <=numero1):
  print("{} ,{} ,{}".format(numero2, numero3, numero3))
if(numero3 <=numero2 and numero2 <=numero1):
  print("{} ,{} ,{}".format(numero3, numero2, numero1))
if(numero3 <=numero1 and numero1 <=numero2):
  print("{} ,{} ,{}".format(numero3, numero1, numero2))
if(numero1 <=numero3 and numero3 <=numero2):
  print("{} ,{} ,{}".format(numero1, numero3, numero2))