num1 = int(input("Ingrese el primer número: "))
num2 = int(input("Ingrese el segundo número: "))
num3 = int(input("Ingrese el tercer número: "))
ordenados = sorted([num1, num2, num3])
print(ordenados[0], ',', ordenados[1], ',', ordenados[2])
