#Ordenar tres números
numero1=int(input())
numero2=int(input())
numero3=int(input())
if(numero1<=numero2<=numero3):
  print(numero1,",",numero2,",",numero3)
else:
  if(numero1<=numero3<=numero2):
      print(numero1,",",numero3,",",numero2)
  else:
      if(numero2<=numero3<=numero1):
        print(numero2,",",numero3,",",numero1)
      else:
          if(numero2<=numero1<=numero3):
            print(numero2,",",numero1,",",numero3)
          else:
              if(numero3<=numero1<=numero2):
                print(numero3,",",numero1,",",numero2)
              else:
                  if(numero3<=numero2<=numero1):
                    print(numero3,",",numero2,",",numero1)