print("ingresa el primer numero:")
num1=int(input())
print("ingresar el segundo numero:")
num2=int(input())
print("ingresar el tercer numero:")
num3=int(input())
mi=min(num1,num2,num3)
ma=max(num1,num2,num3)
mid=(num1+num2+num3-mi-ma)
print("",mi,",",mid,",",ma)