string=input()
b=string.find("b")
d=string.find("d")
e=string.find("e")
f=string.find("f")
g=string.find("g")
h=string.find("h")
i=string.find("i")
j=string.find("j")
k=string.find("k")
l=string.find("l")
m=string.find("m")
n=string.find("n")
o=string.find("o")
p=string.find("p")
q=string.find("q")
r=string.find("r")
s=string.find("s")
u=string.find("u")
v=string.find("v")
w=string.find("w")
x=string.find("x")
y=string.find("y")
z=string.find("z")
if(b!=-1)or(d!=-1)or(e!=-1)or(f!=-1)or(g!=-1)or(h!=-1)or(i!=-1)or(j!=-1)or(k!=-1):
  print("secuencia incorrecta")
elif(l!=-1)or(m!=-1)or(n!=-1)or(o!=-1)or(p!=-1)or(q!=-1)or(r!=-1)or(s!=-1)or(u!=-1):
  print("secuencia incorrecta")
elif(v!=-1)or(x!=-1)or(y!=-1)or(z!=-1)or(w!=-1):
  print("secuencia incorrecta")
else:
  print("secuencia correcta")
  