#Zodiaco
d=int(input("ingrese un d: "))
m=int(input("ingrese un m: "))
if(m==1):
  if(d>=1)and(d<=20):
    print("CAPRICORNIO")
  else:
      print("ACUARIO")
if(m==2):
    if(d>=1)and(d<=19):
      print("ACUERIO")
    else:
      print("PISCIS")
if(m==3):
  if(d>=1)and(d<=21):
      print("PISCIS")
  else:
      print("ARIES")
if(m==4):
    if(d>=1)and(d<=20):
      print("ARIES")
    else:
      print("TAURO")
if(m==5):
    if(d>=1)and(d<=21):
      print("TAURO")
    else:
      print("GEMINIS")
if(m==6):
    if(d>=1)and(d<=21):
      print("GEMINIS")
    else:
      print("CANCER")
if(m==7):
    if(d>=1)and(d<=23):
      print("CANCER")
    else:
      print("LEO")
if(m==8):
    if(d>=1)and(d<=23):
      print("LEO")
    else:
      print("VIRGO")
if(m==9):
    if(d>=1)and(d<=23):
      print("VIRGO")
    else:
      print("LIBRA")
if(m==10):
    if(d>=1)and(d<=23):
      print("LIBRA")
    else:
      print("ECORPION")
if(m==11):
    if(d>=1)and(d<=22):
      print("ESCORPION")
    else:
      print("SAGITARIO")
if(m==12):
    if(d>=1)and(d<=22):
      print("SAGITARIO")
    else:
      print("CAPRICORNIO")     