#Zodiaco
print("Para saber su signo del Zodiaco debe ingresar el día de su cumpleaños")
dia=int(input("Día del mes: "))
mes=int(input("Mes de Nacimiento (en números): "))
if(mes==3)and(21<=dia<=31):
    print("Aries")
elif(mes==4)and(1<=dia<=20):
    print("Aries")
elif(mes==4)and(21<=dia<=30):
    print("Taurus")
elif(mes==5)and(1<=dia<=21):
    print("Taurus")
elif(mes==5)and(22<=dia<=31):
    print("geminis")
elif(mes==6)and(1<=dia<=21):
    print("geminis")
elif(mes==6)and(22<=dia<=30):
    print("Cancer")
elif(mes==7)and(1<=dia<=22):
    print("Cancer")
elif(mes==7)and(23<=dia<=31):
    print("Leo")
elif(mes==8)and(1<=dia<=22):
    print("Leo")
elif(mes==8)and(23<=dia<=31):
    print("Virgo")
elif(mes==9)and(1<=dia<=23):
    print("Virgo")
elif(mes==9)and(24<=dia<=30):
    print("Libra")
elif(mes==10)and(1<=dia<=23):
    print("Libra")
elif(mes==10)and(24<=dia<=31):
    print("escorpio")
elif(mes==11)and(1<=dia<=22):
    print("escorpio")
elif(mes==11)and(23<=dia<=30):
    print("Sagittarius")
elif(mes==12)and(1<=dia<=21):
    print("Sagittarius")
elif(mes==12)and(22<=dia<=31):
    print("Capricorn")
elif(mes==1)and(1<=dia<=20):
    print("Capricorn")
elif(mes==1)and(21<=dia<=31):
    print("Aquarius")
elif(mes==2)and(1<=dia<=19):
    print("Aquarius")
elif(mes==2)and(20<=dia<=29):
    print("Pisces")
elif(mes==3)and(1<=dia<=20):
    print("Pisces")