#Zodiaco
print("SIGNOS DEL ZODIACO")
dia = int(input("ingrese el dia:"))
mes = int(input("ingrese el mes:"))
if(dia>=20 and mes = 1) or (dia<=19 and mes = 2)
    print("SIGNO Acuario")
if(dia >= 19 and mes = 2) or (dia <= 21 and mes = 3)
    print("SIGNO Piscis")
if(dia >= 21 and mes = 3) or (dia <= 20 and mes = 4)
    print("SIGNO Aries")
if(dia >= 20 and mes = 4) or (dia <= 21 and mes = 5)
    print("SIGNO Tauro")
if(dia >= 21 and mes = 5) or (dia <= 21 and mes = 6)
    print("SIGNO Geminis")
if(dia >= 21 and mes = 6) or (dia <= 23 and mes = 7)
    print("SIGNO Cancer")
if(dia >= 23 and mes = 7) or (dia <= 23 and mes = 8)
    print("SIGNO Leo")
if(dia >= 23 and mes = 8) or (dia <= 23 and mes = 9)
    print("SIGNO Virgo")
if(dia >= 23 and mes = 9) or (dia <= 23 and mes = 10)
    print("SIGNO Libra")
if(dia >= 23 and mes = 10) or (dia <= 22 and mes = 11)
    print("SIGNO Escorpio")
if(dia >= 23 and mes = 11) or (dia <= 22 and mes = 12)
    print("SIGNO Sagitario")
if(dia >= 22 and mes = 12) or (dia <= 20 and mes = 1)
    print("SIGNO Capricornio")