#Zodiaco
dia = int(input("Que dia cumples años:"))
mes = int(input("Que mes cumples años:"))
if(dia>=21 and mes == 3): print ("Aries")
elif(dia<=20 and mes == 4): print("Aries")
elif(dia>=21 and mes == 4): print ("Taurus")
elif(dia<=21 and mes == 5): print ("Taurus")
elif(dia>=22 and mes == 5): print ("Gemini")
elif(dia<=21 and mes == 6): print ("Gemini")
elif(dia>=22 and mes == 6): print ("Cancer")
elif(dia<=22 and mes == 7): print ("Cancer")
elif(dia>=23 and mes == 7): print ("Leo")
elif(dia<=22 and mes == 8): print ("Leo")
elif(dia>=23 and mes == 8): print ("Virgo")
elif(dia<=23 and mes == 9): print ("Virgo")
elif(dia>=24 and mes == 9): print ("Libra")
elif(dia<=23 and mes == 10): print ("Libra")
elif(dia>=24 and mes == 10): print ("Scorpio")
elif(dia<=22 and mes == 11): print ("Scorpio")
elif(dia>=23 and mes == 11): print ("Sagittarius")
elif(dia<=21 and mes == 12): print ("Sagittarius")
elif(dia>=22 and mes == 12): print ("Capricornio")
elif(dia<=20 and mes == 1): print ("Capricornio")
elif(dia>=21 and mes == 1): print ("Aquarius")
elif(dia<=19 and mes == 2): print ("Aquarius")
elif(dia>=20 and mes == 2): print ("Piscis")
elif(dia<=20 and mes == 3): print ("Piscis")


