#DM=dia del mes M=mes 
DM=int(input("ingresa el día del mes de tu cumpleanos "))
M=int(input("ingresa el numero del mes de tu cumpleanos "))
if M==3 and DM>=21: print("Aries")
if M==4 and DM<=20: print("Aries")
if M==4 and DM>20: print("Tauro")
if M==5 and DM<=20: print("Tauro")
if M==5 and DM>20: print("Geminis")
if M==6 and DM<=21: print ("Geminis")
if M==6 and DM>20: print("Cancer")
if M==7 and DM<=23: print("Cancer")
if M==7 and DM>23: print("Leo")
if M==8 and DM<=23: print("Leo")
if M==8 and DM>23: print("Virgo")
if M==9 and DM<=23: print("Virgo")
if M==9 and DM>23: print("Libra")
if M==10 and DM<=23: print("Libra")
if M==10 and DM>23: print("Escorpion")
if M==11 and DM<23: print("Escorpion")
if M==11 and DM>23: print("Sagitario")
if M==12 and DM<=23: print("Sagitario")
if M==12 and DM>23: print("Capricornio")
if M==1 and DM<=20: print ("Capricornio")
if M==1 and DM>20: print("Acuario")
if M==2 and DM<19: print ("Acuario")
if M==2 and DM>=19: print("Piscis")
if M==3 and DM<21: print("Piscis")