#Zodiaco
dia=int(input())
mes=int(input())
if(mes==1):
  if(0<dia<21):
    print("Capricornio")
  elif(20<dia<32):
    print("Acuario")
elif(mes==2):
  if(0<dia<20):
    print("Acuario")
  elif(19<dia<29):
    print("Piscis")
elif(mes==3):
  if(0<dia<21):
    print("Piscis")
  elif(20<dia<32):
    print("Aries")
elif(mes==4):
  if(0<dia<21):
    print("Aries")
  elif(20<dia<31):
    print("Tauro")
elif(mes==5):
  if(0<dia<22):
    print("Tauro")
  elif(21<dia<32):
    print("Geminis")
elif(mes==6):
  if(0<dia<22):
    print("Geminis")
  elif(21<dia<31):
    print("Cancer")
elif(mes==7):
  if(0<dia<23):
    print("Cancer")
  elif(22<dia<32):
    print("Leo")
elif(mes==8):
  if(0<dia<23):
    print("Leo")
  elif(22<dia<32):
    print("Virgo")
elif(mes==9):
  if(0<dia<24):
    print("Virgo")
  elif(23<dia<31):
    print("Libra")
elif(mes==10):
  if(0<dia<25):
    print("Libra")
  elif(24<dia<32):
    print("Escorpion")
elif(mes==11):
  if(0<dia<23):
    print("Escorpion")
  elif(22<dia<31):
    print("Sagitario")
elif(mes==12):
  if(0<dia<24):
    print("Sagitario")
  elif(23<dia<32):
    print("Capricornio")