print("ACA SABRAS TU SIGNO ZODIACAL")

print("Progama creado por: Luciano")

DIA_DE_NACIMIENTO_GG= int(input("ingresa por favor tu dia de nacimiento:"))
MES_DE_NACIMIENTO_LUCIANO= int(input("ingresa por favor tu mes de nacimiento:"))

if (MES_DE_NACIMIENTO_LUCIANO==3) and (DIA_DE_NACIMIENTO_GG>21) or (MES_DE_NACIMIENTO_LUCIANO==4) and(DIA_DE_NACIMIENTO_GG<20):
   print("aries")

elif (MES_DE_NACIMIENTO_LUCIANO==4) and (DIA_DE_NACIMIENTO_GG>20) or (MES_DE_NACIMIENTO_LUCIANO==5) and(DIA_DE_NACIMIENTO_GG<21):
   print("tauro")

elif (MES_DE_NACIMIENTO_LUCIANO==5) and (DIA_DE_NACIMIENTO_GG>21) or (MES_DE_NACIMIENTO_LUCIANO==6) and(DIA_DE_NACIMIENTO_GG<21):
   print("geminis")

elif (MES_DE_NACIMIENTO_LUCIANO==6) and (DIA_DE_NACIMIENTO_GG>21) or (MES_DE_NACIMIENTO_LUCIANO==7) and(DIA_DE_NACIMIENTO_GG<23):
   print("cancer")

elif (MES_DE_NACIMIENTO_LUCIANO==7) and (DIA_DE_NACIMIENTO_GG>23) or (MES_DE_NACIMIENTO_LUCIANO==8) and(DIA_DE_NACIMIENTO_GG<23):
   print("leo")

elif (MES_DE_NACIMIENTO_LUCIANO==8) and (DIA_DE_NACIMIENTO_GG>23) or (MES_DE_NACIMIENTO_LUCIANO==9) and(DIA_DE_NACIMIENTO_GG<23):
   print("virgo")

elif (MES_DE_NACIMIENTO_LUCIANO==9) and (DIA_DE_NACIMIENTO_GG>23) or (MES_DE_NACIMIENTO_LUCIANO==10) and(DIA_DE_NACIMIENTO_GG<23):
   print("libra")

elif (MES_DE_NACIMIENTO_LUCIANO==10) and (DIA_DE_NACIMIENTO_GG>23) or (MES_DE_NACIMIENTO_LUCIANO==11) and(DIA_DE_NACIMIENTO_GG<22):
   print("escorpio")

elif (MES_DE_NACIMIENTO_LUCIANO==11) and (DIA_DE_NACIMIENTO_GG>23) or (MES_DE_NACIMIENTO_LUCIANO==12) and(DIA_DE_NACIMIENTO_GG<22):
   print("sagitario")

elif (MES_DE_NACIMIENTO_LUCIANO==12) and (DIA_DE_NACIMIENTO_GG>22) or (MES_DE_NACIMIENTO_LUCIANO==1) and(DIA_DE_NACIMIENTO_GG<20):
   print("capricornio")

elif (MES_DE_NACIMIENTO_LUCIANO==1) and (DIA_DE_NACIMIENTO_GG>20) or (MES_DE_NACIMIENTO_LUCIANO==2) and(DIA_DE_NACIMIENTO_GG<19):
   print("acuario")

elif (MES_DE_NACIMIENTO_LUCIANO==2) and (DIA_DE_NACIMIENTO_GG>19) or (MES_DE_NACIMIENTO_LUCIANO==3) and(DIA_DE_NACIMIENTO_GG<21):
   print("piscis")
