#Zodiaco
D=int(input("Ingrese el número del día en que usted nació:"))
M=int(input("Ingrese el número del mes en que usted nació:"))

if(D>=21 and M==3): print("Aries")
elif(D<=20 and M==4): print("Aries")
elif(D>=21 and M==4): print("Tauro")
elif(D<=21 and M==5): print("Tauro")
elif(D>=22 and M==5): print("Géminis")
elif(D<=21 and M==6): print("Géminis")
elif(D>=22 and M==6): print("Cáncer")
elif(D<=22 and M==7): print("Cáncer")
elif(D>=23 and M==7): print("Leo")
elif(D<=22 and M==8): print("Leo")
elif(D>=23 and M==8): print("Virgo")
elif(D<=23 and M==9): print("Virgo")
elif(D>=24 and M==9): print("Libra")
elif(D<=23 and M==10): print("Libra")
elif(D>=24 and M==10): print("Escorpión")
elif(D<=22 and M==11): print("Escorpión")
elif(D>=23 and M==11): print("Sagitario")
elif(D<=21 and M==12): print("Sagitario")
elif(D>=22 and M==12): print("Capricornio")
elif(D<=20 and M==1): print("Capricornio")
elif(D>=21 and M==1): print("Acuario")
elif(D<=19 and M==2): print("Acuario")
elif(D>=20 and M==2): print("Piscis")
elif(D<=20 and M==3): print("Piscis")
 