d=eval(input(' día de cumpleaños:'))
m=eval(input(' mes de cumpleaños:'))
if m==3 and 21<=d<=31:
    print('Tu signo es Aries')
if m==4 and 1<=d<=20:
    print('Tu signo es Aries')
if m==4 and 21<=d<=30:
    print('Tu signo es Tauro')
if m==5 and 1<=d<=20:
    print('Tu signo es Tauro')
if m==5 and 21<=d<=31:
    print('Tu signo es Géminis')
if m==6 and 1<=d<=20:
    print('Tu signo es Géminis')
if m==6 and 21<=d<=30:
    print('Tu signo es Cancer')
if m==7 and 1<=d<=22:
    print('Tu signo es Cancer')
if m==7 and 23<=d<=31:
    print('Tu signo es Leo')
if m==8 and 1<=d<=22:
    print('Tu signo es Leo')
if m==8 and 23<=d<=31:
    print('Tu signo es Virgo')
if m==9 and 1<=d<=22:
    print('Tu signo es Virgo')
if m==9 and 23<=d<=30:
    print('Tu signo es Libra')
if m==10 and 1<=d<=22:
    print('Tu signo es Libra')
if m==10 and 23<=d<=31:
    print('Tu signo es Escorpio')
if m==11 and 1<=d<=21:
    print('Tu signo es Escorpio')
if m==11 and 22<=d<=30:
    print('Tu signo es Sagitario')
if m==12 and 1<=d<=21:
    print('Tu signo es Sagitario')
if m==12 and 22<=d<=31:
    print('Tu signo es Capricornio')
if m==1 and 1<=d<=19:
    print('Tu signo es Capricornio')
if m==1 and 20<=d<=31:
    print('Tu signo es Acuario')
if m==2 and 1<=d<=18:
    print('Tu signo es Acuario')
if m==2 and 19<=d<=29:
    print('Tu signo es Piscis')
if m==3 and 1<=d<=20:
    print('Tu signo es Piscis')