#Zodiaco
dia=int(input("ingrese un dia: "))
mes=int(input("ingrese un mes: "))
if(mes==1):
  if(dia>=1)and(dia<=20):
    print("CAPRICORNIO")
  else:
      print("ACUARIO")
if(mes==2):
    if(dia>=1)and(dia<=19):
      print("ACUERIO")
    else:
      print("PISCIS")
if(mes==3):
  if(dia>=1)and(dia<=21):
      print("PISCIS")
  else:
      print("ARIES")
if(mes==4):
    if(dia>=1)and(dia<=20):
      print("ARIES")
    else:
      print("TAURO")
if(mes==5):
    if(dia>=1)and(dia<=21):
      print("TAURO")
    else:
      print("GEMINIS")
if(mes==6):
    if(dia>=1)and(dia<=21):
      print("GEMINIS")
    else:
      print("CANCER")
if(mes==7):
    if(dia>=1)and(dia<=23):
      print("CANCER")
    else:
      print("LEO")
if(mes==8):
    if(dia>=1)and(dia<=23):
      print("LEO")
    else:
      print("VIRGO")
if(mes==9):
    if(dia>=1)and(dia<=23):
      print("VIRGO")
    else:
      print("LIBRA")
if(mes==10):
    if(dia>=1)and(dia<=23):
      print("LIBRA")
    else:
      print("ECORPION")
if(mes==11):
    if(dia>=1)and(dia<=22):
      print("ESCORPION")
    else:
      print("SAGITARIO")
if(mes==12):
    if(dia>=1)and(dia<=22):
      print("SAGITARIO")
    else:
      print("CAPRICORNIO")  
      