print("Fecha de cumpleaños")
D=int(input("Dia:"))
M=int(input("Mes:"))
if ((M==3 and D>21) or (M==4 and 20>=D)):print("Aries")
elif ((M==4 and D>=21) or (M==5 and 21>=D)):print("Tauro")
elif(( M==5 and D>=22) or (M==6 and 21>=D)):print("Geminis")
elif ((M==6 and D>=22) or (M==7 and 22>=D)):print("Cáncer")
elif ((M==7 and D>=23) or (M==8 and 22>=D)):print("Leo")
elif ((M==8 and D>=23) or (M==9 and 23>=D)):print("Virgo")
elif ((M==9 and D>=24) or (M==10 and 23>=D)):print("Libra")
elif ((M==10 and D>=24) or (M==11 and 22>=D)):print("Escorpión")
elif ((M==11 and D>=23) or (M==12 and 21>=D)):print("Sagitario")
elif ((M==12 and D>=22) or (M==1 and 20>=D)):print("Capricornio")
elif ((M==1 and D>=21) or (M==2 and 19>=D)):print("Acuario")
elif ((M==2 and D>=20) or (M==3 and 20>=D)):print("Piscis")
