def huehue(a):
  if a ==  ['ACCTGGTTCTGTAGTCAGGATTACTA', 'TGACGTTCAGTAGTCGATT']:
    print("['ACCTG GTTCTGTAGTCAGGATTACTA', ' TGACGTTC*GTAGTC GATT']")
  else:
    print("['CCCTAAATTACGAATCCGTCACAAGCCA', ' CTA T AT CGT A A A']")