#Sistema de Ecuaciones
a=float(input("a: "))
b=float(input("b: "))
c=float(input("c: "))
d=float(input("d: "))
e=float(input("e: "))
f=float(input("f: "))
x=((b*f)-(e*c))/((b*d)-(a*e))
y=((a*f)-(d*c))/((d*(b*-1))+(a*e))
print("x= ",x)
print("y= ",y)