#Sistema de Ecuaciones
print("ecuacion 1")
x1=int(input("x ecuación 1:"))
y1=int(input("y ecuación 1:"))
n1=int(input("n ecuación 1:"))
print("ecuacion2")
x2=int(input("x ecuación 2:"))
y2=int(input("y ecuación 2:"))
n2=int(input("n ecuación 2:"))
D=int(x1*y2-y1*x2)
Dx=int(n1*y2-y1*n2)
Dy=int(x1*n2-n1*x2)
xf=(Dx/D)
yf=(Dy/D)
print("x=",xf)
print("y=",yf)