a= int(input('ingresa un valor para a: '))
b= int(input('ingresa un valor para b: '))
c= int(input('ingresa un valor para c: '))
d= int(input('ingresa un valor para d: '))
e= int(input('ingresa un valor para e: '))
f= int(input('ingresa un valor para f: '))

x=(c*e-f*b)/(a*e-b*d)
y=(a*f-c*d)/(a*e-b*d)
print("x=", x,"y=", y)