#Sistema de Ecuaciones
A=float(input("ingrese el coeficiente de X de la primera ecuacion"))
B=float(input("ingrese el coeficiente de Y de la primera ecuacion"))
C=float(input("ingrese el tercer coeficiente de la primera ecuacion"))
a=float(input("ingrese el coeficiente de X de la segunda ecuacion"))
b=float(input("ingrese el coeficiente de Y de la segunda ecuacion"))
c=float(input("ingrese el tercer coeficiente de la segunda ecuacion"))
print("El sistema de ecuaciones es:")
print(A,"X + ",B,"Y = ",C)
print(a,"X + ",b,"Y = ",c)
X=float((C-(B*c/b))/(A-(B*a/b)))
Y=float((C-A*X)/B)
print("El resultado es:")
print("X= ",X)
print("Y= ",Y)