#Sistema de Ecuaciones
a=float(input())
b=float(input())
c=float(input())
d=float(input())
e=float(input())
f=float(input())
primer=float(b*f-e*c)
segundo=float(b*d-e*a)
x=float(primer/segundo)
tercer=float(c-a*x)
y=float(tercer/b)
valor_x=(round(x,1))
valor_y=(round(y,1))
print("['x=",valor_x,"','y=",valor_y,"]")