#Sistema de Ecuaciones
a=float(input("Ingresa una valor de a"))
b=float(input("Ingresa un valor de b"))
c=float(input("Ingresaa un valor de c"))
print("{0}x+{1}y={2}".format(a,b,c))
d=float(input("Ingresa un valor de d"))
e=float(input("Ingresa un valor de e"))
f=float(input("Ingresa un valor de f"))
ecuacion2=print("{0}x+{1}y={2}".format(d,e,f))
x=float((f*b-e*c)/(d*b-a*e))
y=float((f*a-d*c)/(e*a-b*d))
ro=round(x,1)
rou=round(y,1)
print("x=",ro,"y=",rou)