print("ax+by=c")
print("dx+ey=f")
A=int(input("a= "))
B=int(input("b= "))
C=int(input("c= "))
D=int(input("d= "))
E=int(input("e= "))
F=int(input("f= "))
X = (C*E - B*F)/(A*E - B*D)
round(X,1)
Y = (A*F - C*D)/(A**E - B*D)
round(Y,1)
print("x=",X)
print("y=",Y)