#Sistema de Ecuaciones
a=float(input("ingrese a "))
b=float(input("ingrese b "))
c=float(input("ingrese c "))
a1=float(input("ingrese a1 "))
b1=float(input("ingrese b1 "))
c1=float(input("ingrese a1 "))
m=(a*b1)-(a1*b)
mx=(c*b1)-(c1*b)
my=(a*c1)-(c*a1)
y=round((my/m),1)
x=round((mx/m),1)
print("x=",x)
print("y=",y)      