#Sistema de Ecuacionesprint("Introduzca numeros de manera que el sistema de ecuaciones sea consistente, ademas las ecuaciones no pueden ser linealmente dependientes")
print("Primera ecuación:")
a=float(input("Coeficiente que acompaña a X:"))
b=float(input("Coeficiente que acompaña a Y:"))
c=float(input("Coeficiente resultado:"))
print("Segunda ecuación:")
d=float(input("Coeficiente que acompaña a X:"))
e=float(input("Coeficiente que acompaña a Y:"))
f=float(input("Coeficiente resultado:"))
g=float((d*c-a*f)/(d*b-a*e))
h=round(g,1)
print("y=",h)
i=float((c*e-f*b)/(a*e-d*b))
j=round(i,1)
print("x=",j)