def rot13(palabra):
    palabra=palabra.replace("a","1")
    palabra = palabra.replace("b","2")
    palabra = palabra.replace("c","3")
    palabra = palabra.replace("d","4")
    palabra = palabra.replace("e","5")
    palabra = palabra.replace("f","6")
    palabra = palabra.replace("g","7")
    palabra = palabra.replace("h","8")
    palabra = palabra.replace("i","9")
    palabra = palabra.replace("j","*")
    palabra = palabra.replace("k","+")
    palabra = palabra.replace("l","-")
    palabra = palabra.replace("m","_")
    palabra = palabra.replace("n", "a")
    palabra = palabra.replace("o", "b")
    palabra = palabra.replace("p", "c")
    palabra = palabra.replace("q", "d")
    palabra = palabra.replace("r", "e")
    palabra = palabra.replace("s", "f")
    palabra = palabra.replace("t", "g")
    palabra = palabra.replace("u", "h")
    palabra = palabra.replace("v", "i")
    palabra = palabra.replace("w", "j")
    palabra = palabra.replace("x", "k")
    palabra = palabra.replace("y", "l")
    palabra = palabra.replace("z", "m")
    palabra = palabra.replace("1", "n")
    palabra = palabra.replace("2", "o")
    palabra = palabra.replace("3", "p")
    palabra = palabra.replace("4", "q")
    palabra = palabra.replace("5", "r")
    palabra = palabra.replace("6", "s")
    palabra = palabra.replace("7", "t")
    palabra = palabra.replace("8", "u")
    palabra = palabra.replace("9", "v")
    palabra = palabra.replace("*", "w")
    palabra = palabra.replace("+", "x")
    palabra = palabra.replace("-", "y")
    palabra = palabra.replace("_", "z")
    return palabra

if __name__=="__main__":
    palabra=input("Ingresa la palabra que quieras encriptar: ")
    palabra.lower()
    resultado=rot13(palabra)
    print("El resultado es: ",resultado)
           