def rot13(palabra):
    palabra=palabra.replace("a","n")
    palabra=palabra.replace("b","o")
    palabra=palabra.replace("c","p")
    palabra=palabra.replace("d","q")
    palabra=palabra.replace("e","r")
    palabra=palabra.replace("f","s")
    palabra=palabra.replace("g","t")
    palabra=palabra.replace("h","u")
    palabra=palabra.replace("i","v")
    palabra=palabra.replace("j","w")
    palabra=palabra.replace("k","x")
    palabra=palabra.replace("l","y")
    palabra=palabra.replace("m","z")
    palabra=palabra.replace("n","a")
    palabra=palabra.replace("o","b")
    palabra=palabra.replace("p","c")
    palabra=palabra.replace("q","d")
    palabra=palabra.replace("r","e")
    palabra=palabra.replace("s","f")
    palabra=palabra.replace("t","g")
    palabra=palabra.replace("u","h")
    palabra=palabra.replace("v","i")
    palabra=palabra.replace("w","j")
    palabra=palabra.replace("x","k")
    palabra=palabra.replace("y","l")
    palabra=palabra.replace("z","m")
    return palabra