def jerigonzo(x):
    y=list(x)
    numero_de_a=y.count("a")
    if numero_de_a==1:
        a=y.index("a")
        y.remove(y[a])
        y.insert(a,"p")
        y.insert(a+1,"a")
    if numero_de_a==2:
        a=y.index("a")
        y.remove(y[a])
        aa=y.index("a")
        y.remove(y[aa])
        y.insert(a,"p")
        y.insert(a+1,"a")
        y.insert(aa,"p")
        y.insert(aa+1,"a")
    if numero_de_a==3:
        a=y.index("a")
        y.remove(y[a])
        aa=y.index("a")
        y.remove(y[aa])
        aaa=y.index("a")
        y.remove(y[aaa])
        y.insert(a,"a")
        y.insert(a+1,"p")
        y.insert(a+2,"a")
        y.insert(aa+3,"a")
        y.insert(aa+4,"p")
        y.insert(aa+5,"a")
        y.insert(aaa+6,"a")
        y.insert(aaa+7,"p")
        y.insert(aaa+8,"a")
    numero_de_e=y.count("e")
    if numero_de_e==1:
        e=y.index("e")
        y.remove(y[e])
        y.insert(e,"e")
        y.insert(e+1,"p")
        y.insert(e+2,"e")
    if numero_de_e==2:
        e=y.index("e")
        y.remove(y[e])
        ee=y.index("e")
        y.remove(y[ee])
        y.insert(e,"p")
        y.insert(e+1,"e")
        y.insert(ee+2,"p")
        y.insert(ee+3,"e")
    if numero_de_e==3:
        e=y.index("e")
        y.remove(y[e])
        ee=y.index("e")
        y.remove(y[ee])
        eee=y.index("e")
        y.remove(y[eee])
        y.insert(e,"p")
        y.insert(e+1,"a")
        y.insert(ee,"p")
        y.insert(ee+1,"a")
        y.insert(eee,"p")
        y.insert(eee+1,"a")
    numero_de_o=y.count("o")
    if numero_de_o==1:
        o=y.index("o")
        y.remove(y[o])
        y.insert(o,"p")
        y.insert(o+1,"o")
    if numero_de_o==2:
        o=y.index("o")
        y.remove([o])
        oo=y.index("o")
        y.remove(y[oo])
        y.insert(o,"p")
        y.insert(o+1,"o")
        y.insert(oo,"p")
        y.insert(oo+1,"o")
    if numero_de_o==3:
        o=y.index("o")
        y.remove(y[o])
        oo=y.index("o")
        y.remove(y[oo])
        ooo=y.index("o")
        y.remove(y[ooo])
        y.insert(o,"o")
        y.insert(o+1,"p")
        y.insert(o+2,"o")
        y.insert(oo+3,"o")
        y.insert(oo+4,"p")
        y.insert(oo+5,"o")
        y.insert(ooo+6,"o")
        y.insert(ooo+7,"p")
        y.insert(ooo+8,"o")
    w= "".join(y)
    return w