def jerigonzo(x):
  #ENTRADA DEL PROGRAMA...
  MOVMENT = ""
  #PROCESAMIENTO...
  for letterMEGA in x:
        if letterMEGA in "aAeEiIoOuU":
            #AÑADIENDO LETRAS P Y VOCALES PARA JERIGONZO...
            MOVMENT += letterMEGA
            #AÑADIENDO "P"
            MOVMENT += "p"
            #FINAL...
        MOVMENT += letterMEGA
  #SALIDA...
  return MOVMENT
         