#Cálculo del dígito verificador de un rut
RUT = str(int(input("Ingrese RUT a verificar: ")))
contador = len(str(RUT))
if(contador==8):
    D1 = int(RUT[0])
    D2 = int(RUT[1])
    D3 = int(RUT[2])
    D4 = int(RUT[3])
    D5 = int(RUT[4])
    D6 = int(RUT[5])
    D7 = int(RUT[6])
    D8 = int(RUT[7])
    a = (D8*2)
    b = (D7*3)
    c = (D6*4)
    d = (D5*5)
    e = (D4*6)
    f = (D3*7)
    g = (D2*2)
    h = (D1*3)
    suma = (a+b+c+d+e+f+g+h)
if(contador==7):
    D1 = int(RUT[0])
    D2 = int(RUT[1])
    D3 = int(RUT[2])
    D4 = int(RUT[3])
    D5 = int(RUT[4])
    D6 = int(RUT[5])
    D7 = int(RUT[6])
    a = (D7*2)
    b = (D6*3)
    c = (D5*4)
    d = (D4*5)
    e = (D3*6)
    f = (D2*7)
    g = (D1*2)
    suma = (a+b+c+d+e+f+g)
division = int(suma/11)
resto = suma-(11*division)
dv = (11-resto)
if(dv==11):
    dv=0
if(dv==10):
    dv="K"
print("El RUT verificado es: ",RUT,"-",dv, sep="")
print("dv=",dv,sep="")