import math
a = int(input("Ingrese su rut sin el codigo verificador para que este sea calculado: "))
DIEZMILLONESIMA = math.trunc(a / 10000000 )
MILLONESIMA = math.trunc(a % 10000000 / 1000000 )
CIENMILESIMA = math.trunc(a % 1000000 / 100000 )
DIEZMILESIMA = math.trunc(a % 100000 / 10000 )
MILESIMA =  math.trunc(a % 10000 / 1000 )
CENTESIMA = math.trunc(a % 1000 / 100 )
DECIMA = math.trunc(a % 100 / 10 )
UNIDAD = math.trunc(a % 10 / 1 )
print(CENTESIMA)
#Calculos digito verificador:
RESULTADO_UNIDAD = UNIDAD * 2
RESULTADO_DECIMA = DECIMA * 3
RESULTADO_CENTESIMA = CENTESIMA * 4
RESULTADO_MILESIMA = MILESIMA * 5
RESULTADO_DIEZMILESIMA = DIEZMILESIMA * 6
RESULTADO_CIENMILESIMA = CIENMILESIMA * 7
RESULTADO_MILLONESIMA = MILLONESIMA * 2
RESULTADO_DIEZMILLONESIMA = DIEZMILLONESIMA * 3
SUMA_RESULTADOS = RESULTADO_UNIDAD + RESULTADO_DECIMA + RESULTADO_CENTESIMA + RESULTADO_MILESIMA + RESULTADO_DIEZMILESIMA + RESULTADO_CIENMILESIMA + RESULTADO_MILLONESIMA + RESULTADO_DIEZMILLONESIMA
PARTE_ENTERA = math.trunc(SUMA_RESULTADOS / 11)
RESTO_DIVISION = SUMA_RESULTADOS - (11 * PARTE_ENTERA)
RESULTADO_FINAL = 11 - RESTO_DIVISION
if RESULTADO_FINAL == 11:
    print("dv=", end="")
    print(0)
elif RESULTADO_FINAL == 10:
    print("dv=", end="")
    print("k")
else:
    print("dv=", end="")
    print(RESULTADO_FINAL)
