numero=int(input("ingrese numero de hasta 4 digitos:"))
miles= int (numero/1000)
cen=int ((numero-(miles*1000))/100)
dec= int ((numero-(miles*1000 + cen*100))/10)
unidal= int ((numero-(miles*1000 + cen*100 + dec*10)))
a=str (miles)
b=str (cen)
c=str(dec)
d=str(unidal)
print(a+"M+"+b+"C+"+c+"D+"+d+"U")