#Descomponer un número
num=str(input("Ingrese un número: "))
suma=(num[0]) + (num[1]) + (num[2]) + (num[3])
print(suma)
a=(num[0])
b=(num[1])
c=(num[2])
d=(num[3])
print(a, "M")
print(b, "C")
print(c, "D")
print(d, "U")      