PT = float(input("Ingrese nota tareas: "))
PI = float(input("Ingrese nota interrogaciones: "))
NE = float(input("Ingrese nota Examen: "))
PP = float(input("Ingrese nota Presentacion: "))
promedio = (0.3 * PT) + (0.3 * PI) + (0.3 * NE) + (0.1 * PP)
print("El promedio de tus notas es:",promedio) 