nota1=float(input("nota numero uno : "))
nota2=float(input("nota numero dos : "))
nota3=float(input("nota tres : "))
nota4=float(input("nota cuatro : "))
notafinal= (0.3*nota1+0.3*nota2+0.3*nota3+0.1*nota4) 
print (notafinal)