PT=float(input("ingresa tu nota: "))
PI=float(input("ingresa tu nota: "))
NE=float(input("ingresa tu nota: "))
PP=float(input("ingresa tu nota: "))
promedio=(0.3*PT)+(0.3*PI)+(0.3*NE)+(0.1*PP)
print(round(promedio,1))