PT=float(input("ingrese nota de la tarea:"))
PI=float(input("ingrese nota de la interrogacion:"))
NE=float(input("ingrese nota del examen:"))
PP=float(input("ingrese nota de la prsentacion:"))
notas=(0.3*PT+0.3*PI+0.3*NE+0.1*PP)
print(notas)