n1=float(input("ingrese su nota 1: "))
n2=float(input("ingrese su nota 2: "))
n3=float(input("ingrese su nota 3: "))
n4=float(input("ingrese su nota 4: "))
promedio=(n1*0.3+n2*0.3+n3*0.3+n4*0.1)
print(round(promedio,1))   