T=float(input("Promedio de tareas:"))
I=float(input("Promedio de interrogaciones:"))
E=float(input("Nota examen:"))
P=float(input("Nota presentacion:"))
NF=(0.3*T)+(0.3*I)+(0.3*E)+(0.1*P)
NF=float(NF)
print(NF)