PT=input("Ingresa el PROMEDIO DE TUS TAREAS")
PI=input("Ingresa el PROMEDIO DE LAS I")
NE=input("pon la nota del EXAMEN")
PP=input("pon la nota de presentacion")
PT=float(PT)
PI=float(PI)
NE=float(NE)
PP=float(PP)
print (0.3*PT + 0.3*PI + 0.3*NE + 0.1*PP)