PT = float(input("Ingresa tu nota por tareas: "))
PI = float(input("Ingresa tu nota por interrogaciones: "))
NE = float(input("Ingresa tu nota por examenes: "))
PP = float(input("Ingresa tu nota por presentacion: "))
Resultado = (0.3*PT)+(0.3*PI)+(0.3*NE)+(0.1*PP)
print("Su promedio es: ",Resultado)