PT = float(input("ingrese nota de tareas"))
PI = float(input("ingrese nota de interrogaciones"))
NE = float(input("ingrese nota de examen"))
PP = float(input("ingrese nota de Presentacion"))
NotaFinal = float(round(0.3*PT + 0.3*PI + 0.3*NE + 0.1*PP,1))
print("la nota final es", NotaFinal)      