pt=float(input("ingrese la nota de tareas: "))
pi=float(input("ingrese la nota de interrogaciones: "))
ne=float(input("ingrese la nota de examen: "))
pp=float(input("ingrese la nota de presentacion: "))
x=((0.3*pt)+(0.3*pi)+(0.3*ne)+(0.1*pp))
a=round(x,1)
print(a)