a=float(input("Tareas="))
b=float(input("Interrogaciones="))
c=float(input("Examen="))
d=float(input("Presentacion="))
e=int((0.3 * a + 0.3 * b + 0.3 * c + 0.1 * d) * 10)
f=float(e/10)
print(str(f))     