a=float(input("Ingrese nota tareas"))
b=float(input("Ingrese nota interrogaciones"))
c=float(input("Ingrese nota examen"))
d=float(input("Ingrese nota presentación"))
e=(0.3*a)+(0.3*b)+(0.3*c)+(0.1*d)
print(round(e,1))