PT=float(input("ingrese el promedio de tareas"))
PI=float(input("ingrese el promedio de intwrrogaciones"))
NE=float(input("ingrese la nota de examen"))
PP=float(input("ingrese la nota de presentacion"))
PF=round(0.3*PT+0.3*PI+0.3*NE+0.1*PP,1)
print("tu promedio final es: ",PF)