print("la nota de sus tareas")
PT = float(input())
print("La nota de interrogaciones")
PI = float(input())
print("La nota de sus examen")
NE = float(input())
print("La nota de presentacion")
PP = float(input())
promediofinal = (0.3*PT) + (0.3*PI) + (0.3*NE) +  (0.1*PP)
promediofinal2 = round(promediofinal,1)
print("El promedio final es:" , promediofinal2)