PT = float(input("ingrese su nota de tareas: "))
PI = float(input("ingrese su nota de interrogaciones: "))
NE = float(input("ingrese su nota de examen: "))
PP = float(input("ingrese su nota de presentacion: "))
prom = (0.3PT + 0.3PI + 0.3NE + 0.1PP)
print("su promedio es: ",prom)