print("ingrese sus notas")
A=float(input("tareas: "))
B=float(input("interrogantes: "))
C=float(input("examen: ")) 
D=float(input("presentacion: ")) 
A1=(A*(3/10))
B1=(B*(3/10))
C1=(C*(3/10))
D1=(D*(1/10))
PROMEDIO=(A1+B1+C1+D1)
print("promedio del estudiante es",PROMEDIO)
