n1=float(input("ingrese nota:"))
n2=float(input("ingrese nota:"))
n3=float(input("ingrese nota:"))
n4=float(input("ingrese nota:"))
p1=(n1*0.3)+(n2*0.3)+(n3*0.3)+(n4*0.1)
promedio=round(p1//4)
print(promedio)