PT = float(input("ingrese la nota de tareas : "))
PI = float(input("ingrese la nota de interrograciones : "))
NE = float(input("ingrese la nota deL examen : "))
PP = float(input("ingrese la nota de la presentacion: "))
PF = (0.3*PT) + (0.3*PI) + (0.3*NE) + (0.1*PP)
print("su promedio final es : " , (PF))