pt=eval(input("Promedio de Notas: "))
pi=eval(input("Promedio de Interrogaciones:"))
ne=eval(input("Nota de Examen: "))
pp=eval(input("Promedio de Presentacion: "))
promedio= round(0.3*pt+0.3*pi+0.3*ne+0.1*pp,1)
print('el promedio final es:',promedio)