PT = float(input("Nota de tareas: "))
PI = float(input("Nota de Interrogaciones: "))
NE = float(input("Nota de examen: "))
PP = float(input("Nota de presentacion: "))
PF =(0.3 * PT ) + (0.3 * PI) + (0.3 * NE) + (0.1 * PP)
print(round(PF, 1 ))