print("ingrese sus cuatro notas:")
PT= float(input("tareas"))
PI= float(input("interrogaciones"))
NE= float(input("examen"))
PP= float(input("presentacion"))
x=(PT*0.3+PI*0.3+NE*0.3+ PP*0.1)
print(round(x,1))