pt = float(input("ingrese nota 1: "))
pi = float(input("ingrese nota 2: "))
ne = float(input("ingrese nota 3: "))
pp = float(input("ingrese nota 4: "))
pf = (pt*0.3 + pi*0.3 + ne*0.3 + pp*0.1)
print(pf)   