#Nota final
print("ingrese nota tarea")
pt=float(input())
print("ingrese nota interrogacion")
pi=float(input())
print("ingrese nota examen")
ne=float(input())
print("ingrese nota presentacion")
pp=float(input())
nt=(0.3*pt+ 0.3*pi + 0.3*ne + 0.1*pp)
notafinal=round(nt,2)
print ("su nota final es",notafinal)
