Pt = float(input("Tareas: "))
Pi = float(input("Interrogaciones:"))
Ne = float(input("Examen: "))
PP = float(input("Presentacion:"))
res = (((0.3 * Pt) + (0.3 * Pi) + ( 0.3 * Ne) + (0.1* PP )))
promedio = (res)
x = (round(promedio, 1))
print(x)