n1=eval(input("Ingrese nota: "))
n2=eval(input("Ingrese nota: "))
n3=eval(input("Ingrese nota: "))
n4=eval(input("Ingrese nota: "))
c=(0.3*n1)+(0.3*n2)+(0.3*n3)+(0.1*n4)
print("Su nota final es: ", round(c, 1))