#Nota final
PT= float(input("ingrese nota tarea:" ))
PI= float(input("ingrese nota interrogacion:" ))
NE= float(input("ingrese nota examen:" ))
PP= float(input("ingrese nota presentacion:" ))
round(PT)
round(PI)
round(NE)
round(PP)
Pfinal=((0.3*PT)+(0.3*PI)+(0.3*NE)+(0.1*PP))
print(Pfinal)
round(Pfinal)